### ISSUE TITLE
Gradient of GoogLeNet outputs gives ValueError: graph contains cycles

### ISSUE THREAD

**Issue by JesseLivezey** [sklearn-theano/sklearn-theano#83] opened 2015-08-26 20:08 UTC
I'm not sure if something is happening in sklearn-theano to cause this error, or if I'm doing something wrong w.r.t. theano. I'm getting cycles in the graph, but I'm not sure how.

I'd like to calculate dP(y=0)/dX (or similar derivatives).

This compiles fine
```
import theano
import theano.tensor as T

from sklearn_theano.feature_extraction.caffe.googlenet import create_theano_expressions

blobs, data_inputs = create_theano_expressions()
out = blobs['loss3/loss3']
test = out.sum()
grad = T.grad(test, data_inputs)

func = theano.function(inputs=[data_inputs], outputs=out)
```

but if the outputs of the function is ```grad``` rather than ```out```, I get the ```ValueError: graph contains cycles```
```
import theano
import theano.tensor as T

from sklearn_theano.feature_extraction.caffe.googlenet import create_theano_expressions

blobs, data_inputs = create_theano_expressions()
out = blobs['loss3/loss3']
test = out.sum()
grad = T.grad(test, data_inputs)

func = theano.function(inputs=[data_inputs], outputs=grad)
```

Any ideas? Am I doing something obviously wrong? Also, is there a mailinglist for this project? It's referenced in the docs, but I couldn't find one.

**Comment by eickenberg** [comment] 2015-08-26 20:16
Not from what I can tell. Thanks for raising this - as it happens I will be needing the gradient as well very soon ;)

This is rather curious indeed. Hopefully with a simple explanation.

I can't debug this right now, but what I'd try is to choose an output that is much closer to the input and try the same thing. That way you can bisect your way to where this cycle must lie and we can look from there. Hope to be able to look at this soon myself, too.

**Comment by JesseLivezey** [comment] 2015-08-27 18:29
Starting from what I believe is the first layer in the network, these are okay:
```
conv1/7x7_s2
pool1/3x3_s2
pool1/norm1
conv2/3x3_reduce
conv2/3x3
conv2/norm2
```
and this is the first to break
```
pool2/3x3_s2
```
For completeness, here are all of the blobs:
```
data
label
label_data_1_split_0
label_data_1_split_1
label_data_1_split_2
conv1/7x7_s2
pool1/3x3_s2
pool1/norm1
conv2/3x3_reduce
conv2/3x3
conv2/norm2
pool2/3x3_s2
pool2/3x3_s2_pool2/3x3_s2_0_split_0
pool2/3x3_s2_pool2/3x3_s2_0_split_1
pool2/3x3_s2_pool2/3x3_s2_0_split_2
pool2/3x3_s2_pool2/3x3_s2_0_split_3
inception_3a/1x1
inception_3a/3x3_reduce
inception_3a/3x3
inception_3a/5x5_reduce
inception_3a/5x5
inception_3a/pool
inception_3a/pool_proj
inception_3a/output
inception_3a/output_inception_3a/output_0_split_0
inception_3a/output_inception_3a/output_0_split_1
inception_3a/output_inception_3a/output_0_split_2
inception_3a/output_inception_3a/output_0_split_3
inception_3b/1x1
inception_3b/3x3_reduce
inception_3b/3x3
inception_3b/5x5_reduce
inception_3b/5x5
inception_3b/pool
inception_3b/pool_proj
inception_3b/output
pool3/3x3_s2
pool3/3x3_s2_pool3/3x3_s2_0_split_0
pool3/3x3_s2_pool3/3x3_s2_0_split_1
pool3/3x3_s2_pool3/3x3_s2_0_split_2
pool3/3x3_s2_pool3/3x3_s2_0_split_3
inception_4a/1x1
inception_4a/3x3_reduce
inception_4a/3x3
inception_4a/5x5_reduce
inception_4a/5x5
inception_4a/pool
inception_4a/pool_proj
inception_4a/output
inception_4a/output_inception_4a/output_0_split_0
inception_4a/output_inception_4a/output_0_split_1
inception_4a/output_inception_4a/output_0_split_2
inception_4a/output_inception_4a/output_0_split_3
inception_4a/output_inception_4a/output_0_split_4
loss1/ave_pool
loss1/conv
loss1/fc
loss1/classifier
loss1/loss1
inception_4b/1x1
inception_4b/3x3_reduce
inception_4b/3x3
inception_4b/5x5_reduce
inception_4b/5x5
inception_4b/pool
inception_4b/pool_proj
inception_4b/output
inception_4b/output_inception_4b/output_0_split_0
inception_4b/output_inception_4b/output_0_split_1
inception_4b/output_inception_4b/output_0_split_2
inception_4b/output_inception_4b/output_0_split_3
inception_4c/1x1
inception_4c/3x3_reduce
inception_4c/3x3
inception_4c/5x5_reduce
inception_4c/5x5
inception_4c/pool
inception_4c/pool_proj
inception_4c/output
inception_4c/output_inception_4c/output_0_split_0
inception_4c/output_inception_4c/output_0_split_1
inception_4c/output_inception_4c/output_0_split_2
inception_4c/output_inception_4c/output_0_split_3
inception_4d/1x1
inception_4d/3x3_reduce
inception_4d/3x3
inception_4d/5x5_reduce
inception_4d/5x5
inception_4d/pool
inception_4d/pool_proj
inception_4d/output
inception_4d/output_inception_4d/output_0_split_0
inception_4d/output_inception_4d/output_0_split_1
inception_4d/output_inception_4d/output_0_split_2
inception_4d/output_inception_4d/output_0_split_3
inception_4d/output_inception_4d/output_0_split_4
loss2/ave_pool
loss2/conv
loss2/fc
loss2/classifier
loss2/loss1
inception_4e/1x1
inception_4e/3x3_reduce
inception_4e/3x3
inception_4e/5x5_reduce
inception_4e/5x5
inception_4e/pool
inception_4e/pool_proj
inception_4e/output
pool4/3x3_s2
pool4/3x3_s2_pool4/3x3_s2_0_split_0
pool4/3x3_s2_pool4/3x3_s2_0_split_1
pool4/3x3_s2_pool4/3x3_s2_0_split_2
pool4/3x3_s2_pool4/3x3_s2_0_split_3
inception_5a/1x1
inception_5a/3x3_reduce
inception_5a/3x3
inception_5a/5x5_reduce
inception_5a/5x5
inception_5a/pool
inception_5a/pool_proj
inception_5a/output
inception_5a/output_inception_5a/output_0_split_0
inception_5a/output_inception_5a/output_0_split_1
inception_5a/output_inception_5a/output_0_split_2
inception_5a/output_inception_5a/output_0_split_3
inception_5b/1x1
inception_5b/3x3_reduce
inception_5b/3x3
inception_5b/5x5_reduce
inception_5b/5x5
inception_5b/pool
inception_5b/pool_proj
inception_5b/output
pool5/7x7_s1
loss3/classifier
loss3/loss3
```

**Comment by eickenberg** [comment] 2015-08-27 19:32
ok cool, thanks for the effort. i will try to figure out what is happening
here.

fwiw, there is a pr removing a function called fancy_maxpool, which i had
to implement to make theano 0.6 be able to do the caffe models. the pr
simplifies the graph quite a bit, so there is a slight chance it may work
with that. it sits on current master, so it would be the only change if you
check it out.

**Comment by eickenberg** [comment] 2015-08-28 22:56
On my laptop your code runs as is for current sklearn-theano master. I am on the `0.7.0` theano release right now.

**Comment by JesseLivezey** [comment] 2015-08-28 23:56
Are you sure you didn't have the new pooling branch open? On sklearn-theano master and theano master, I get the same crash. If I use your pooling PR, then it seems to work fine.

**Comment by nouiz** [comment] 2015-08-31 15:35
We introduced in Theano a problem that cause this ~2week ago. This PR
should fix it:

https://github.com/Theano/Theano/pull/3344

This could be the cause of the problem described here.

**Comment by JesseLivezey** [comment] 2015-09-03 20:24
@eickenberg 
The fix @nouiz suggested also seemed to fix the problem for me.

**Comment by kastnerkyle** [comment] 2015-09-19 11:24
This is merged into Theano master now. Closing

**Closed by kastnerkyle** 2015-09-19 11:24 UTC
Labels: bug

**Comment by eickenberg** [comment] 2015-09-19 11:29
Don't think so - #78 sitll open

**Comment by kastnerkyle** [comment] 2015-09-19 11:32
I took the last comment from @JesseLivezey to mean that using the Theano PR also fixed the problem, without #78. If this is not the case, we can reopen

**Comment by eickenberg** [comment] 2015-09-19 11:33
OK I misunderstood! Yes, that's right. So yeah, that issue can stay closed.

**Comment by kastnerkyle** [comment] 2015-09-19 11:35
Also, I should say that I am using https://github.com/memisevic/artify/blob/master/artify.py#L104 to do basically this and it seems OK so far.
